*** Variables ***
${PageTitle}            id:id_title
${FistNameLabel}        id:id_label_fn
${LastNameLabel}        id:id_label_ln
${EmailLabel}           id:id_label_ea
${PhoneLabel}           id:id_label_ph
${GenderLabel}          id:id_label_ge
${MenGenderLabel}       id:id_label_gm
${WomenGenderLabel}     id:id_label_gf
${StateLabel}           id:id_label_st
${TermsLabel}           id:id_terms
${ResetButton Value}    id:id_reset_button
${SubmitButton Value}   id:id_submit_button
